# -*- coding: utf-8 -*-
from openerp import models, fields, api
import logging

_logger = logging.getLogger(__name__)


class Area(models.Model):
    
    _name = 'leaf.area'
    
    global_id = fields.Char(string='Unique ID for the area autogenerated')
    external_id = fields.Char(string='External ID used by system users to define an area')
    name = fields.Char(string='Name of area')
    a_type = fields.Char(string='Identifier of the area type', required=True)
    